config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check
  resources :kittens
  # Defines the root path route ("/")
  root "kittens#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all
    flash.now[:notice] = "We have exactly #{@kittens.size} kittens registered."
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @kittens }
    end
  end
  def new
    @kitten = Kitten.new 
  end
  def create
    @kitten = Kitten.new(kitten_params)

    if @kitten.save
      redirect_to @kitten , notice: "Congrats, you have successfully registered your cat"
    else
      render :new, status: :unprocessable_entity, notice: "Error, something went wrong"
    end
  end

  def show
    @kitten = Kitten.find(params[:id])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @kitten }
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(params[:id])

    if @kitten.update(kitten_params)
      redirect_to @kitten , notice: "Congrats, you have successfully updated information of your cat"
    else
      render :edit, status: :unprocessable_entity , notice: "Error, something went wrong"
    end
  end
  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.destroy

    redirect_to root_path, status: :see_other, notice: "You have successfully deleted your kitten"
  end
  private
    def kitten_params
      params.require(:kitten).permit(:name, :age , :cuteness , :softness)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_with model: kitten do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>

  </div>

  <div>
    <%= form.label :age %><br>
    <%= form.number_field :age %><br>
  </div>

  <div>
    <%= form.label :cuteness %><br>
    <%= form.number_field :cuteness %><br>
  </div>

  <div>
    <%= form.label :softness %><br>
    <%= form.number_field :softness %><br>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/kittens/edit.html.erb
<h1>Edit Your Kitten</h1>

<%= render "form", kitten: @kitten %>

app/views/kittens/index.html.erb
<h1>Kittens</h1>

<ul>
  <% @kittens.each do |kitten| %>
    <li>
      <%= link_to kitten.name, kitten %>
    </li>
    <ul>
    <li><%= link_to "Edit", edit_kitten_path(kitten) %></li>
    <li><%= link_to "Destroy", kitten_path(kitten), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
    </ul>
  <% end %>
</ul>

app/views/kittens/new.html.erb
<h1>Register Your Kitten</h1>

<%= render "form", kitten: @kitten %>

app/views/kittens/show.html.erb
<h1><%= @kitten.name %></h1>
<p>Cuteness: <%= @kitten.cuteness %></p>
<p>Age: <%= @kitten.age %></p>
<p>Softness: <%= @kitten.softness %></p>
<ul>
  <li><%= link_to "Edit", edit_kitten_path(@kitten) %></li>
   <li><%= link_to "Destroy", kitten_path(@kitten), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
<div>
    <%= notice %>
  </div>
  <body>
    <%= yield %>
  </body>
</html>